In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("./dataset/solar_radiation_raw.csv")

C:\Users\sudha\AppData\Local\Temp\ipykernel_6640\1666651912.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("./dataset/solar_radiation_raw.csv")

In [3]:
df.head()

,time,ghi_pyr,dni,dhi,air_temperature,relative_humidity,wind_speed,wind_speed_of_gust,wind_from_direction_st_dev,wind_from_direction,barometric_pressure,sensor_cleaning,comments,actual_date,day_lenght
0,2014-10-25 13:10:00,628.3,652.3,191.3,25.5,46.9,3.9,6.4,12.7,266.0,948.3,0.0,NaN,2014-10-25,662
1,2014-10-25 13:20:00,618.6,654.6,186.6,25.3,47.2,3.8,5.6,13.6,257.0,948.1,0.0,NaN,2014-10-25,662
2,2014-10-25 13:30:00,603.9,649.1,184.5,25.4,46.4,4.0,5.6,12.9,261.0,948.1,0.0,NaN,2014-10-25,662
3,2014-10-25 13:40:00,584.1,635.7,182.6,25.5,46.2,3.4,5.6,14.2,255.8,948.0,0.0,NaN,2014-10-25,662
4,2014-10-25 13:50:00,564.7,624.9,180.0,25.4,47.1,4.5,6.9,14.1,265.8,947.9,0.0,NaN,2014-10-25,662

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 15 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   time                        132258 non-null  object
 1   ghi_pyr                     131762 non-null  float64
 2   dni                         117760 non-null  float64
 3   dhi                         117760 non-null  float64
 4   air_temperature             131762 non-null  float64
 5   relative_humidity           131762 non-null  float64
 6   wind_speed                  131762 non-null  float64
 7   wind_speed_of_gust          131762 non-null  float64
 8   wind_from_direction_st_dev  131762 non-null  float64
 9   wind_from_direction         131762 non-null  float64
 10  barometric_pressure         131762 non-null  float64
 11  sensor_cleaning             131762 non-null  float64
 12  comments                    14498 non-null   object
 13  actual_date                 132258 non-null  object
 14  day_lenght                  132258 non-null  int64
dtypes: float64(11), int64(1), object(3)
memory usage: 15.1+ MB

In [5]:
df=df.drop_duplicates()

In [6]:
df.shape

(132258, 15)

In [7]:
for column in df.columns:
    if df[column].dtype in ['float64']:
        df[column].fillna(df[column].mean(), inplace=True)

In [8]:
df= df.drop('comments',axis=1)

In [9]:
df.isnull().sum()

time                          0
ghi_pyr                       0
dni                           0
dhi                           0
air_temperature               0
relative_humidity             0
wind_speed                    0
wind_speed_of_gust            0
wind_from_direction_st_dev    0
wind_from_direction           0
barometric_pressure           0
sensor_cleaning               0
actual_date                   0
day_lenght                    0
dtype: int64

In [10]:
from scipy import stats
for column in df.columns:
    if df[column].dtype in ['int64', 'float64']:
        z_scores = stats.zscore(df[column])
        outliers = (abs(z_scores) > 3)
        print(f"Column: {column}")
        print("\n")
        print("Outliers:", outliers)

Column: ghi_pyr


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: ghi_pyr, Length: 132258, dtype: bool
Column: dni


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: dni, Length: 132258, dtype: bool
Column: dhi


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: dhi, Length: 132258, dtype: bool
Column: air_temperature


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: air_temperature, Length: 132258, dtype: bool
Column: relative_humidity


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: relative_humidity, Length: 132258, dtype: bool
Column: wind_speed


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: wind_speed, Length: 132258, dtype: bool
Column: wind_speed_of_gust


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: wind_speed_of_gust, Length: 132258, dtype: bool
Column: wind_from_direction_st_dev


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: wind_from_direction_st_dev, Length: 132258, dtype: bool
Column: wind_from_direction


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: wind_from_direction, Length: 132258, dtype: bool
Column: barometric_pressure


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: barometric_pressure, Length: 132258, dtype: bool
Column: sensor_cleaning


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: sensor_cleaning, Length: 132258, dtype: bool
Column: day_lenght


Outliers: 0         False
1         False
2         False
3         False
4         False
          ...
132253    False
132254    False
132255    False
132256    False
132257    False
Name: day_lenght, Length: 132258, dtype: bool

In [13]:
#df.to_csv("./dataset/solar_radiation_cleaned.csv", index=False)